### ISSUE TITLE
Expected type String, got type Symbol with value :debug

### ISSUE THREAD

**Issue by SalvatoreT** [claui/homebrew-whence#2]
I ran into this error when trying a simple `brew whence adb` after downloading this extension.

Are you open to PRs to fix?

```
❯ brew whence adb
Error: Parameter 'names': Expected type String, got type Symbol with value :debug
Caller: /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11517/lib/types/private/methods/call_validation.rb:133
Definition: /opt/homebrew/Library/Homebrew/cli/parser.rb:200 (Homebrew::CLI::Parser#switch)
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11517/lib/types/configuration.rb:296:in `call_validation_error_handler_default'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11517/lib/types/configuration.rb:303:in `call_validation_error_handler'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11517/lib/types/private/methods/call_validation.rb:310:in `report_error'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11517/lib/types/private/methods/call_validation.rb:136:in `block in validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11517/lib/types/private/methods/signature.rb:222:in `block in each_args_value_type'
<internal:numeric>:237:in `times'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11517/lib/types/private/methods/signature.rb:221:in `each_args_value_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11517/lib/types/private/methods/call_validation.rb:133:in `validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11517/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
/opt/homebrew/Library/Taps/claui/homebrew-whence/cmd/brew-whence.rb:49:in `block in whence_args'
/opt/homebrew/Library/Homebrew/cli/parser.rb:191:in `instance_eval'
/opt/homebrew/Library/Homebrew/cli/parser.rb:191:in `initialize'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11517/lib/types/private/methods/call_validation.rb:167:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11517/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11517/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
/opt/homebrew/Library/Taps/claui/homebrew-whence/cmd/brew-whence.rb:42:in `new'
/opt/homebrew/Library/Taps/claui/homebrew-whence/cmd/brew-whence.rb:42:in `whence_args'
/opt/homebrew/Library/Taps/claui/homebrew-whence/cmd/brew-whence.rb:54:in `whence'
/opt/homebrew/Library/Taps/claui/homebrew-whence/cmd/brew-whence.rb:103:in `<module:Homebrew>'
/opt/homebrew/Library/Taps/claui/homebrew-whence/cmd/brew-whence.rb:36:in `<top (required)>'
<internal:/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:11:in `require?'
/opt/homebrew/Library/Homebrew/brew.rb:102:in `<main>'
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/claui/homebrew-whence/issues/new
```

**Comment by claui** [comment]
Hi @SalvatoreT, thanks for your offer. I no longer use Homebrew so I can no longer maintain this external command.
